//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for connectorStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="connectorStyle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Rectlinear"/>
 *     &lt;enumeration value="Oblique"/>
 *     &lt;enumeration value="Curve"/>
 *     &lt;enumeration value="Round Oblique"/>
 *     &lt;enumeration value="Round Rectlinear"/>
 *     &lt;enumeration value="Follow Diagram"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "connectorStyle")
@XmlEnum
public enum ConnectorStyle {

    @XmlEnumValue("Rectlinear")
    RECTLINEAR("Rectlinear"),
    @XmlEnumValue("Oblique")
    OBLIQUE("Oblique"),
    @XmlEnumValue("Curve")
    CURVE("Curve"),
    @XmlEnumValue("Round Oblique")
    ROUND_OBLIQUE("Round Oblique"),
    @XmlEnumValue("Round Rectlinear")
    ROUND_RECTLINEAR("Round Rectlinear"),

    /**
     * "Follow Diagram" should not be set to a diagram, it is for connector only
     * 
     */
    @XmlEnumValue("Follow Diagram")
    FOLLOW_DIAGRAM("Follow Diagram");
    private final String value;

    ConnectorStyle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConnectorStyle fromValue(String v) {
        for (ConnectorStyle c: ConnectorStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
