//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visual-paradigm.com/product/vpuml/modelexporter}property">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramRef" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diagramRef"
})
@XmlRootElement(name = "DiagramRefProperty")
public class DiagramRefProperty
    extends Property
{

    @XmlElement(name = "DiagramRef")
    protected DiagramRef diagramRef;

    /**
     * Gets the value of the diagramRef property.
     * 
     * @return
     *     possible object is
     *     {@link DiagramRef }
     *     
     */
    public DiagramRef getDiagramRef() {
        return diagramRef;
    }

    /**
     * Sets the value of the diagramRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagramRef }
     *     
     */
    public void setDiagramRef(DiagramRef value) {
        this.diagramRef = value;
    }

}
