//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Model" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DiagramComment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice minOccurs="0">
 *                   &lt;element name="DiagramCommentProperties">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}StringProperty"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelOrDiagramComment"
})
@XmlRootElement(name = "DiagramComments")
public class DiagramComments {

    @XmlElements({
        @XmlElement(name = "Model", type = Model.class),
        @XmlElement(name = "DiagramComment", type = DiagramComments.DiagramComment.class)
    })
    protected List<Object> modelOrDiagramComment;

    /**
     * Gets the value of the modelOrDiagramComment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelOrDiagramComment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelOrDiagramComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Model }
     * {@link DiagramComments.DiagramComment }
     * 
     * 
     */
    public List<Object> getModelOrDiagramComment() {
        if (modelOrDiagramComment == null) {
            modelOrDiagramComment = new ArrayList<Object>();
        }
        return this.modelOrDiagramComment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice minOccurs="0">
     *         &lt;element name="DiagramCommentProperties">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}StringProperty"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="content" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diagramCommentProperties"
    })
    public static class DiagramComment {

        @XmlElement(name = "DiagramCommentProperties")
        protected DiagramComments.DiagramComment.DiagramCommentProperties diagramCommentProperties;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "summary")
        protected String summary;
        @XmlAttribute(name = "author")
        protected String author;
        @XmlAttribute(name = "dateTime")
        protected String dateTime;
        @XmlAttribute(name = "content")
        protected String content;

        /**
         * Gets the value of the diagramCommentProperties property.
         * 
         * @return
         *     possible object is
         *     {@link DiagramComments.DiagramComment.DiagramCommentProperties }
         *     
         */
        public DiagramComments.DiagramComment.DiagramCommentProperties getDiagramCommentProperties() {
            return diagramCommentProperties;
        }

        /**
         * Sets the value of the diagramCommentProperties property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiagramComments.DiagramComment.DiagramCommentProperties }
         *     
         */
        public void setDiagramCommentProperties(DiagramComments.DiagramComment.DiagramCommentProperties value) {
            this.diagramCommentProperties = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the summary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSummary() {
            return summary;
        }

        /**
         * Sets the value of the summary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSummary(String value) {
            this.summary = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the dateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDateTime() {
            return dateTime;
        }

        /**
         * Sets the value of the dateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDateTime(String value) {
            this.dateTime = value;
        }

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded" minOccurs="0">
         *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}StringProperty"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stringProperty"
        })
        public static class DiagramCommentProperties {

            @XmlElement(name = "StringProperty")
            protected List<StringProperty> stringProperty;

            /**
             * Gets the value of the stringProperty property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stringProperty property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStringProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link StringProperty }
             * 
             * 
             */
            public List<StringProperty> getStringProperty() {
                if (stringProperty == null) {
                    stringProperty = new ArrayList<StringProperty>();
                }
                return this.stringProperty;
            }

        }

    }

}
