//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for diagramElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="diagramElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramElementProperties" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ClauseRegions" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ElseRegion" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Lifelines" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}TimeUnits" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ColumnWidthInfos" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ColumnFilterInfos" minOccurs="0"/>
 *         &lt;element name="BeginArrowHead" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}arrowHead" minOccurs="0"/>
 *         &lt;element name="EndArrowHead" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}arrowHead" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DurationConstraints" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}FreehandPoints" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ElementFont" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Line" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Icons" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Rows" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}MessageUIModelFlowInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ChildShapes" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}FillColor" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ShapeGroup" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}CompartmentFont" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}CompartmentColorModels" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="shapeType" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="model" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="zorder" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isGroupedChild" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="layerId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="displayModelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="classifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="documentaiton_plainText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="taskTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subprocessTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="triggerModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gatewayTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="graphicShapeType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "diagramElement", propOrder = {
    "diagramElementProperties",
    "clauseRegions",
    "elseRegion",
    "lifelines",
    "timeUnits",
    "columnWidthInfos",
    "columnFilterInfos",
    "beginArrowHead",
    "endArrowHead",
    "durationConstraints",
    "freehandPoints",
    "elementFont",
    "line",
    "icons",
    "rows",
    "messageUIModelFlowInfo",
    "childShapes",
    "fillColor",
    "shapeGroup",
    "compartmentFont",
    "compartmentColorModels"
})
@XmlSeeAlso({
    Connector.class,
    Shape.class
})
public abstract class DiagramElement {

    @XmlElement(name = "DiagramElementProperties")
    protected DiagramElementProperties diagramElementProperties;
    @XmlElement(name = "ClauseRegions")
    protected ClauseRegions clauseRegions;
    @XmlElement(name = "ElseRegion")
    protected ElseRegion elseRegion;
    @XmlElement(name = "Lifelines")
    protected Lifelines lifelines;
    @XmlElement(name = "TimeUnits")
    protected TimeUnits timeUnits;
    @XmlElement(name = "ColumnWidthInfos")
    protected ColumnWidthInfos columnWidthInfos;
    @XmlElement(name = "ColumnFilterInfos")
    protected ColumnFilterInfos columnFilterInfos;
    @XmlElement(name = "BeginArrowHead")
    protected ArrowHead beginArrowHead;
    @XmlElement(name = "EndArrowHead")
    protected ArrowHead endArrowHead;
    @XmlElement(name = "DurationConstraints")
    protected DurationConstraints durationConstraints;
    @XmlElement(name = "FreehandPoints")
    protected FreehandPoints freehandPoints;
    @XmlElement(name = "ElementFont")
    protected ElementFont elementFont;
    @XmlElement(name = "Line")
    protected Line line;
    @XmlElement(name = "Icons")
    protected Icons icons;
    @XmlElement(name = "Rows")
    protected Rows rows;
    @XmlElement(name = "MessageUIModelFlowInfo")
    protected MessageUIModelFlowInfo messageUIModelFlowInfo;
    @XmlElement(name = "ChildShapes")
    protected ChildShapes childShapes;
    @XmlElement(name = "FillColor")
    protected FillColor fillColor;
    @XmlElement(name = "ShapeGroup")
    protected ShapeGroup shapeGroup;
    @XmlElement(name = "CompartmentFont")
    protected CompartmentFont compartmentFont;
    @XmlElement(name = "CompartmentColorModels")
    protected CompartmentColorModels compartmentColorModels;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "shapeType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shapeType;
    @XmlAttribute(name = "model")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String model;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "x")
    protected BigInteger x;
    @XmlAttribute(name = "y")
    protected BigInteger y;
    @XmlAttribute(name = "width")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger width;
    @XmlAttribute(name = "height")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger height;
    @XmlAttribute(name = "zorder")
    protected BigInteger zorder;
    @XmlAttribute(name = "isGroupedChild")
    protected Boolean isGroupedChild;
    @XmlAttribute(name = "layerId")
    protected String layerId;
    @XmlAttribute(name = "modelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modelType;
    @XmlAttribute(name = "displayModelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayModelType;
    @XmlAttribute(name = "classifier")
    protected String classifier;
    @XmlAttribute(name = "documentaiton_plainText")
    protected String documentaitonPlainText;
    @XmlAttribute(name = "taskTypeModelType")
    protected String taskTypeModelType;
    @XmlAttribute(name = "subprocessTypeModelType")
    protected String subprocessTypeModelType;
    @XmlAttribute(name = "triggerModelType")
    protected String triggerModelType;
    @XmlAttribute(name = "resultModelType")
    protected String resultModelType;
    @XmlAttribute(name = "gatewayTypeModelType")
    protected String gatewayTypeModelType;
    @XmlAttribute(name = "graphicShapeType")
    protected String graphicShapeType;

    /**
     * Gets the value of the diagramElementProperties property.
     * 
     * @return
     *     possible object is
     *     {@link DiagramElementProperties }
     *     
     */
    public DiagramElementProperties getDiagramElementProperties() {
        return diagramElementProperties;
    }

    /**
     * Sets the value of the diagramElementProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagramElementProperties }
     *     
     */
    public void setDiagramElementProperties(DiagramElementProperties value) {
        this.diagramElementProperties = value;
    }

    /**
     * Gets the value of the clauseRegions property.
     * 
     * @return
     *     possible object is
     *     {@link ClauseRegions }
     *     
     */
    public ClauseRegions getClauseRegions() {
        return clauseRegions;
    }

    /**
     * Sets the value of the clauseRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClauseRegions }
     *     
     */
    public void setClauseRegions(ClauseRegions value) {
        this.clauseRegions = value;
    }

    /**
     * Gets the value of the elseRegion property.
     * 
     * @return
     *     possible object is
     *     {@link ElseRegion }
     *     
     */
    public ElseRegion getElseRegion() {
        return elseRegion;
    }

    /**
     * Sets the value of the elseRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElseRegion }
     *     
     */
    public void setElseRegion(ElseRegion value) {
        this.elseRegion = value;
    }

    /**
     * Gets the value of the lifelines property.
     * 
     * @return
     *     possible object is
     *     {@link Lifelines }
     *     
     */
    public Lifelines getLifelines() {
        return lifelines;
    }

    /**
     * Sets the value of the lifelines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lifelines }
     *     
     */
    public void setLifelines(Lifelines value) {
        this.lifelines = value;
    }

    /**
     * Gets the value of the timeUnits property.
     * 
     * @return
     *     possible object is
     *     {@link TimeUnits }
     *     
     */
    public TimeUnits getTimeUnits() {
        return timeUnits;
    }

    /**
     * Sets the value of the timeUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeUnits }
     *     
     */
    public void setTimeUnits(TimeUnits value) {
        this.timeUnits = value;
    }

    /**
     * Gets the value of the columnWidthInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnWidthInfos }
     *     
     */
    public ColumnWidthInfos getColumnWidthInfos() {
        return columnWidthInfos;
    }

    /**
     * Sets the value of the columnWidthInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnWidthInfos }
     *     
     */
    public void setColumnWidthInfos(ColumnWidthInfos value) {
        this.columnWidthInfos = value;
    }

    /**
     * Gets the value of the columnFilterInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnFilterInfos }
     *     
     */
    public ColumnFilterInfos getColumnFilterInfos() {
        return columnFilterInfos;
    }

    /**
     * Sets the value of the columnFilterInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnFilterInfos }
     *     
     */
    public void setColumnFilterInfos(ColumnFilterInfos value) {
        this.columnFilterInfos = value;
    }

    /**
     * Gets the value of the beginArrowHead property.
     * 
     * @return
     *     possible object is
     *     {@link ArrowHead }
     *     
     */
    public ArrowHead getBeginArrowHead() {
        return beginArrowHead;
    }

    /**
     * Sets the value of the beginArrowHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrowHead }
     *     
     */
    public void setBeginArrowHead(ArrowHead value) {
        this.beginArrowHead = value;
    }

    /**
     * Gets the value of the endArrowHead property.
     * 
     * @return
     *     possible object is
     *     {@link ArrowHead }
     *     
     */
    public ArrowHead getEndArrowHead() {
        return endArrowHead;
    }

    /**
     * Sets the value of the endArrowHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrowHead }
     *     
     */
    public void setEndArrowHead(ArrowHead value) {
        this.endArrowHead = value;
    }

    /**
     * Gets the value of the durationConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link DurationConstraints }
     *     
     */
    public DurationConstraints getDurationConstraints() {
        return durationConstraints;
    }

    /**
     * Sets the value of the durationConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationConstraints }
     *     
     */
    public void setDurationConstraints(DurationConstraints value) {
        this.durationConstraints = value;
    }

    /**
     * Gets the value of the freehandPoints property.
     * 
     * @return
     *     possible object is
     *     {@link FreehandPoints }
     *     
     */
    public FreehandPoints getFreehandPoints() {
        return freehandPoints;
    }

    /**
     * Sets the value of the freehandPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreehandPoints }
     *     
     */
    public void setFreehandPoints(FreehandPoints value) {
        this.freehandPoints = value;
    }

    /**
     * Gets the value of the elementFont property.
     * 
     * @return
     *     possible object is
     *     {@link ElementFont }
     *     
     */
    public ElementFont getElementFont() {
        return elementFont;
    }

    /**
     * Sets the value of the elementFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementFont }
     *     
     */
    public void setElementFont(ElementFont value) {
        this.elementFont = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link Line }
     *     
     */
    public Line getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link Line }
     *     
     */
    public void setLine(Line value) {
        this.line = value;
    }

    /**
     * Gets the value of the icons property.
     * 
     * @return
     *     possible object is
     *     {@link Icons }
     *     
     */
    public Icons getIcons() {
        return icons;
    }

    /**
     * Sets the value of the icons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Icons }
     *     
     */
    public void setIcons(Icons value) {
        this.icons = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link Rows }
     *     
     */
    public Rows getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rows }
     *     
     */
    public void setRows(Rows value) {
        this.rows = value;
    }

    /**
     * Gets the value of the messageUIModelFlowInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MessageUIModelFlowInfo }
     *     
     */
    public MessageUIModelFlowInfo getMessageUIModelFlowInfo() {
        return messageUIModelFlowInfo;
    }

    /**
     * Sets the value of the messageUIModelFlowInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageUIModelFlowInfo }
     *     
     */
    public void setMessageUIModelFlowInfo(MessageUIModelFlowInfo value) {
        this.messageUIModelFlowInfo = value;
    }

    /**
     * Gets the value of the childShapes property.
     * 
     * @return
     *     possible object is
     *     {@link ChildShapes }
     *     
     */
    public ChildShapes getChildShapes() {
        return childShapes;
    }

    /**
     * Sets the value of the childShapes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildShapes }
     *     
     */
    public void setChildShapes(ChildShapes value) {
        this.childShapes = value;
    }

    /**
     * Gets the value of the fillColor property.
     * 
     * @return
     *     possible object is
     *     {@link FillColor }
     *     
     */
    public FillColor getFillColor() {
        return fillColor;
    }

    /**
     * Sets the value of the fillColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillColor }
     *     
     */
    public void setFillColor(FillColor value) {
        this.fillColor = value;
    }

    /**
     * Gets the value of the shapeGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ShapeGroup }
     *     
     */
    public ShapeGroup getShapeGroup() {
        return shapeGroup;
    }

    /**
     * Sets the value of the shapeGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShapeGroup }
     *     
     */
    public void setShapeGroup(ShapeGroup value) {
        this.shapeGroup = value;
    }

    /**
     * Gets the value of the compartmentFont property.
     * 
     * @return
     *     possible object is
     *     {@link CompartmentFont }
     *     
     */
    public CompartmentFont getCompartmentFont() {
        return compartmentFont;
    }

    /**
     * Sets the value of the compartmentFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompartmentFont }
     *     
     */
    public void setCompartmentFont(CompartmentFont value) {
        this.compartmentFont = value;
    }

    /**
     * Gets the value of the compartmentColorModels property.
     * 
     * @return
     *     possible object is
     *     {@link CompartmentColorModels }
     *     
     */
    public CompartmentColorModels getCompartmentColorModels() {
        return compartmentColorModels;
    }

    /**
     * Sets the value of the compartmentColorModels property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompartmentColorModels }
     *     
     */
    public void setCompartmentColorModels(CompartmentColorModels value) {
        this.compartmentColorModels = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the shapeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapeType() {
        return shapeType;
    }

    /**
     * Sets the value of the shapeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapeType(String value) {
        this.shapeType = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setX(BigInteger value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setY(BigInteger value) {
        this.y = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the zorder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZorder() {
        return zorder;
    }

    /**
     * Sets the value of the zorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZorder(BigInteger value) {
        this.zorder = value;
    }

    /**
     * Gets the value of the isGroupedChild property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsGroupedChild() {
        return isGroupedChild;
    }

    /**
     * Sets the value of the isGroupedChild property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsGroupedChild(Boolean value) {
        this.isGroupedChild = value;
    }

    /**
     * Gets the value of the layerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayerId() {
        return layerId;
    }

    /**
     * Sets the value of the layerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayerId(String value) {
        this.layerId = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the displayModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayModelType() {
        return displayModelType;
    }

    /**
     * Sets the value of the displayModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayModelType(String value) {
        this.displayModelType = value;
    }

    /**
     * Gets the value of the classifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassifier() {
        return classifier;
    }

    /**
     * Sets the value of the classifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassifier(String value) {
        this.classifier = value;
    }

    /**
     * Gets the value of the documentaitonPlainText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentaitonPlainText() {
        return documentaitonPlainText;
    }

    /**
     * Sets the value of the documentaitonPlainText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentaitonPlainText(String value) {
        this.documentaitonPlainText = value;
    }

    /**
     * Gets the value of the taskTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskTypeModelType() {
        return taskTypeModelType;
    }

    /**
     * Sets the value of the taskTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskTypeModelType(String value) {
        this.taskTypeModelType = value;
    }

    /**
     * Gets the value of the subprocessTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubprocessTypeModelType() {
        return subprocessTypeModelType;
    }

    /**
     * Sets the value of the subprocessTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubprocessTypeModelType(String value) {
        this.subprocessTypeModelType = value;
    }

    /**
     * Gets the value of the triggerModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerModelType() {
        return triggerModelType;
    }

    /**
     * Sets the value of the triggerModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerModelType(String value) {
        this.triggerModelType = value;
    }

    /**
     * Gets the value of the resultModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultModelType() {
        return resultModelType;
    }

    /**
     * Sets the value of the resultModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultModelType(String value) {
        this.resultModelType = value;
    }

    /**
     * Gets the value of the gatewayTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayTypeModelType() {
        return gatewayTypeModelType;
    }

    /**
     * Sets the value of the gatewayTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayTypeModelType(String value) {
        this.gatewayTypeModelType = value;
    }

    /**
     * Gets the value of the graphicShapeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicShapeType() {
        return graphicShapeType;
    }

    /**
     * Sets the value of the graphicShapeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicShapeType(String value) {
        this.graphicShapeType = value;
    }

}
