//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ClauseRegion" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clauseRegion"
})
@XmlRootElement(name = "ElseRegion")
public class ElseRegion {

    @XmlElement(name = "ClauseRegion")
    protected ClauseRegion clauseRegion;

    /**
     * Gets the value of the clauseRegion property.
     * 
     * @return
     *     possible object is
     *     {@link ClauseRegion }
     *     
     */
    public ClauseRegion getClauseRegion() {
        return clauseRegion;
    }

    /**
     * Sets the value of the clauseRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClauseRegion }
     *     
     */
    public void setClauseRegion(ClauseRegion value) {
        this.clauseRegion = value;
    }

}
