//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for modelRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modelRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="modelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displayModelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="iconPath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentId" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="parentModelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="parentDisplayModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="taskTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subprocessTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="triggerModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gatewayTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="graphicShapeType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="triggerType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modelRef")
@XmlSeeAlso({
    RelationshipRef.class
})
public class ModelRef {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "modelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modelType;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "displayModelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayModelType;
    @XmlAttribute(name = "iconPath")
    protected String iconPath;
    @XmlAttribute(name = "parentId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentId;
    @XmlAttribute(name = "parentModelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentModelType;
    @XmlAttribute(name = "parentDisplayModelType")
    protected String parentDisplayModelType;
    @XmlAttribute(name = "parentName")
    protected String parentName;
    @XmlAttribute(name = "taskTypeModelType")
    protected String taskTypeModelType;
    @XmlAttribute(name = "subprocessTypeModelType")
    protected String subprocessTypeModelType;
    @XmlAttribute(name = "triggerModelType")
    protected String triggerModelType;
    @XmlAttribute(name = "resultModelType")
    protected String resultModelType;
    @XmlAttribute(name = "gatewayTypeModelType")
    protected String gatewayTypeModelType;
    @XmlAttribute(name = "graphicShapeType")
    protected String graphicShapeType;
    @XmlAttribute(name = "triggerType")
    protected String triggerType;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayModelType() {
        return displayModelType;
    }

    /**
     * Sets the value of the displayModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayModelType(String value) {
        this.displayModelType = value;
    }

    /**
     * Gets the value of the iconPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * Sets the value of the iconPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconPath(String value) {
        this.iconPath = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentId(String value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the parentModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentModelType() {
        return parentModelType;
    }

    /**
     * Sets the value of the parentModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentModelType(String value) {
        this.parentModelType = value;
    }

    /**
     * Gets the value of the parentDisplayModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentDisplayModelType() {
        return parentDisplayModelType;
    }

    /**
     * Sets the value of the parentDisplayModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentDisplayModelType(String value) {
        this.parentDisplayModelType = value;
    }

    /**
     * Gets the value of the parentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * Sets the value of the parentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentName(String value) {
        this.parentName = value;
    }

    /**
     * Gets the value of the taskTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskTypeModelType() {
        return taskTypeModelType;
    }

    /**
     * Sets the value of the taskTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskTypeModelType(String value) {
        this.taskTypeModelType = value;
    }

    /**
     * Gets the value of the subprocessTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubprocessTypeModelType() {
        return subprocessTypeModelType;
    }

    /**
     * Sets the value of the subprocessTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubprocessTypeModelType(String value) {
        this.subprocessTypeModelType = value;
    }

    /**
     * Gets the value of the triggerModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerModelType() {
        return triggerModelType;
    }

    /**
     * Sets the value of the triggerModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerModelType(String value) {
        this.triggerModelType = value;
    }

    /**
     * Gets the value of the resultModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultModelType() {
        return resultModelType;
    }

    /**
     * Sets the value of the resultModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultModelType(String value) {
        this.resultModelType = value;
    }

    /**
     * Gets the value of the gatewayTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayTypeModelType() {
        return gatewayTypeModelType;
    }

    /**
     * Sets the value of the gatewayTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayTypeModelType(String value) {
        this.gatewayTypeModelType = value;
    }

    /**
     * Gets the value of the graphicShapeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicShapeType() {
        return graphicShapeType;
    }

    /**
     * Sets the value of the graphicShapeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicShapeType(String value) {
        this.graphicShapeType = value;
    }

    /**
     * Gets the value of the triggerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * Sets the value of the triggerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerType(String value) {
        this.triggerType = value;
    }

}
