//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="2">
 *         &lt;element name="DefaultClassDiagram" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramRef"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DefaultERD" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramRef"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="defaultDatabase" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="supportDatabases" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultClassDiagramOrDefaultERD"
})
@XmlRootElement(name = "ORMInfo")
public class ORMInfo {

    @XmlElements({
        @XmlElement(name = "DefaultClassDiagram", type = ORMInfo.DefaultClassDiagram.class),
        @XmlElement(name = "DefaultERD", type = ORMInfo.DefaultERD.class)
    })
    protected List<Object> defaultClassDiagramOrDefaultERD;
    @XmlAttribute(name = "defaultDatabase")
    protected BigInteger defaultDatabase;
    @XmlAttribute(name = "supportDatabases")
    protected BigInteger supportDatabases;

    /**
     * Gets the value of the defaultClassDiagramOrDefaultERD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultClassDiagramOrDefaultERD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultClassDiagramOrDefaultERD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORMInfo.DefaultClassDiagram }
     * {@link ORMInfo.DefaultERD }
     * 
     * 
     */
    public List<Object> getDefaultClassDiagramOrDefaultERD() {
        if (defaultClassDiagramOrDefaultERD == null) {
            defaultClassDiagramOrDefaultERD = new ArrayList<Object>();
        }
        return this.defaultClassDiagramOrDefaultERD;
    }

    /**
     * Gets the value of the defaultDatabase property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefaultDatabase() {
        return defaultDatabase;
    }

    /**
     * Sets the value of the defaultDatabase property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefaultDatabase(BigInteger value) {
        this.defaultDatabase = value;
    }

    /**
     * Gets the value of the supportDatabases property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSupportDatabases() {
        return supportDatabases;
    }

    /**
     * Sets the value of the supportDatabases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSupportDatabases(BigInteger value) {
        this.supportDatabases = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramRef"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diagramRef"
    })
    public static class DefaultClassDiagram {

        @XmlElement(name = "DiagramRef", required = true)
        protected DiagramRef diagramRef;

        /**
         * Gets the value of the diagramRef property.
         * 
         * @return
         *     possible object is
         *     {@link DiagramRef }
         *     
         */
        public DiagramRef getDiagramRef() {
            return diagramRef;
        }

        /**
         * Sets the value of the diagramRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiagramRef }
         *     
         */
        public void setDiagramRef(DiagramRef value) {
            this.diagramRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramRef"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diagramRef"
    })
    public static class DefaultERD {

        @XmlElement(name = "DiagramRef", required = true)
        protected DiagramRef diagramRef;

        /**
         * Gets the value of the diagramRef property.
         * 
         * @return
         *     possible object is
         *     {@link DiagramRef }
         *     
         */
        public DiagramRef getDiagramRef() {
            return diagramRef;
        }

        /**
         * Sets the value of the diagramRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiagramRef }
         *     
         */
        public void setDiagramRef(DiagramRef value) {
            this.diagramRef = value;
        }

    }

}
