//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ORMInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}RequirementEnumerationInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}LogicalView" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ormInfoOrRequirementEnumerationInfoOrLogicalView"
})
@XmlRootElement(name = "ProjectInfo")
public class ProjectInfo {

    @XmlElements({
        @XmlElement(name = "ORMInfo", type = ORMInfo.class),
        @XmlElement(name = "RequirementEnumerationInfo", type = RequirementEnumerationInfo.class),
        @XmlElement(name = "LogicalView", type = LogicalView.class)
    })
    protected List<Object> ormInfoOrRequirementEnumerationInfoOrLogicalView;

    /**
     * Gets the value of the ormInfoOrRequirementEnumerationInfoOrLogicalView property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ormInfoOrRequirementEnumerationInfoOrLogicalView property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getORMInfoOrRequirementEnumerationInfoOrLogicalView().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORMInfo }
     * {@link RequirementEnumerationInfo }
     * {@link LogicalView }
     * 
     * 
     */
    public List<Object> getORMInfoOrRequirementEnumerationInfoOrLogicalView() {
        if (ormInfoOrRequirementEnumerationInfoOrLogicalView == null) {
            ormInfoOrRequirementEnumerationInfoOrLogicalView = new ArrayList<Object>();
        }
        return this.ormInfoOrRequirementEnumerationInfoOrLogicalView;
    }

}
