//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ProjectInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Models" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}Diagrams" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="umlVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exporterVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="company" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textualAnalysisHighlightCaseSensitive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="documentationType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="html"/>
 *             &lt;enumeration value="plainText"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="commentTableSortColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="commentTableSortAscending" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="containsUseCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="containsStereotype" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="projectPublisherBasePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exportedFromDifferentName" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="nickname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectInfo",
    "models",
    "diagrams"
})
@XmlRootElement(name = "Project")
public class Project {

    @XmlElement(name = "ProjectInfo")
    protected ProjectInfo projectInfo;
    @XmlElement(name = "Models")
    protected Models models;
    @XmlElement(name = "Diagrams")
    protected Diagrams diagrams;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "umlVersion")
    protected String umlVersion;
    @XmlAttribute(name = "exporterVersion")
    protected String exporterVersion;
    @XmlAttribute(name = "author")
    protected String author;
    @XmlAttribute(name = "company")
    protected String company;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "textualAnalysisHighlightCaseSensitive")
    protected Boolean textualAnalysisHighlightCaseSensitive;
    @XmlAttribute(name = "documentationType")
    protected String documentationType;
    @XmlAttribute(name = "commentTableSortColumn")
    protected String commentTableSortColumn;
    @XmlAttribute(name = "commentTableSortAscending")
    protected Boolean commentTableSortAscending;
    @XmlAttribute(name = "containsUseCase")
    protected Boolean containsUseCase;
    @XmlAttribute(name = "containsStereotype")
    protected Boolean containsStereotype;
    @XmlAttribute(name = "projectPublisherBasePath")
    protected String projectPublisherBasePath;
    @XmlAttribute(name = "exportedFromDifferentName")
    protected Boolean exportedFromDifferentName;
    @XmlAttribute(name = "nickname")
    protected String nickname;

    /**
     * Gets the value of the projectInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfo }
     *     
     */
    public ProjectInfo getProjectInfo() {
        return projectInfo;
    }

    /**
     * Sets the value of the projectInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfo }
     *     
     */
    public void setProjectInfo(ProjectInfo value) {
        this.projectInfo = value;
    }

    /**
     * Gets the value of the models property.
     * 
     * @return
     *     possible object is
     *     {@link Models }
     *     
     */
    public Models getModels() {
        return models;
    }

    /**
     * Sets the value of the models property.
     * 
     * @param value
     *     allowed object is
     *     {@link Models }
     *     
     */
    public void setModels(Models value) {
        this.models = value;
    }

    /**
     * Gets the value of the diagrams property.
     * 
     * @return
     *     possible object is
     *     {@link Diagrams }
     *     
     */
    public Diagrams getDiagrams() {
        return diagrams;
    }

    /**
     * Sets the value of the diagrams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Diagrams }
     *     
     */
    public void setDiagrams(Diagrams value) {
        this.diagrams = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the umlVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmlVersion() {
        return umlVersion;
    }

    /**
     * Sets the value of the umlVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmlVersion(String value) {
        this.umlVersion = value;
    }

    /**
     * Gets the value of the exporterVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterVersion() {
        return exporterVersion;
    }

    /**
     * Sets the value of the exporterVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterVersion(String value) {
        this.exporterVersion = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the textualAnalysisHighlightCaseSensitive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTextualAnalysisHighlightCaseSensitive() {
        return textualAnalysisHighlightCaseSensitive;
    }

    /**
     * Sets the value of the textualAnalysisHighlightCaseSensitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTextualAnalysisHighlightCaseSensitive(Boolean value) {
        this.textualAnalysisHighlightCaseSensitive = value;
    }

    /**
     * Gets the value of the documentationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentationType() {
        return documentationType;
    }

    /**
     * Sets the value of the documentationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentationType(String value) {
        this.documentationType = value;
    }

    /**
     * Gets the value of the commentTableSortColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentTableSortColumn() {
        return commentTableSortColumn;
    }

    /**
     * Sets the value of the commentTableSortColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentTableSortColumn(String value) {
        this.commentTableSortColumn = value;
    }

    /**
     * Gets the value of the commentTableSortAscending property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommentTableSortAscending() {
        return commentTableSortAscending;
    }

    /**
     * Sets the value of the commentTableSortAscending property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommentTableSortAscending(Boolean value) {
        this.commentTableSortAscending = value;
    }

    /**
     * Gets the value of the containsUseCase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContainsUseCase() {
        return containsUseCase;
    }

    /**
     * Sets the value of the containsUseCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContainsUseCase(Boolean value) {
        this.containsUseCase = value;
    }

    /**
     * Gets the value of the containsStereotype property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContainsStereotype() {
        return containsStereotype;
    }

    /**
     * Sets the value of the containsStereotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContainsStereotype(Boolean value) {
        this.containsStereotype = value;
    }

    /**
     * Gets the value of the projectPublisherBasePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectPublisherBasePath() {
        return projectPublisherBasePath;
    }

    /**
     * Sets the value of the projectPublisherBasePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectPublisherBasePath(String value) {
        this.projectPublisherBasePath = value;
    }

    /**
     * Gets the value of the exportedFromDifferentName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExportedFromDifferentName() {
        return exportedFromDifferentName;
    }

    /**
     * Sets the value of the exportedFromDifferentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExportedFromDifferentName(Boolean value) {
        this.exportedFromDifferentName = value;
    }

    /**
     * Gets the value of the nickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * Sets the value of the nickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNickname(String value) {
        this.nickname = value;
    }

}
