//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="CompartmentColorModel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="proxy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="foreground" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}color" />
 *                 &lt;attribute name="background" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}color" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "compartmentColorModel"
})
@XmlRootElement(name = "CompartmentColorModels")
public class CompartmentColorModels {

    @XmlElement(name = "CompartmentColorModel")
    protected List<CompartmentColorModels.CompartmentColorModel> compartmentColorModel;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the compartmentColorModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compartmentColorModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompartmentColorModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompartmentColorModels.CompartmentColorModel }
     * 
     * 
     */
    public List<CompartmentColorModels.CompartmentColorModel> getCompartmentColorModel() {
        if (compartmentColorModel == null) {
            compartmentColorModel = new ArrayList<CompartmentColorModels.CompartmentColorModel>();
        }
        return this.compartmentColorModel;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="proxy" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="foreground" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}color" />
     *       &lt;attribute name="background" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}color" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CompartmentColorModel {

        @XmlAttribute(name = "proxy")
        protected String proxy;
        @XmlAttribute(name = "foreground")
        protected String foreground;
        @XmlAttribute(name = "background")
        protected String background;

        /**
         * Gets the value of the proxy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProxy() {
            return proxy;
        }

        /**
         * Sets the value of the proxy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProxy(String value) {
            this.proxy = value;
        }

        /**
         * Gets the value of the foreground property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForeground() {
            return foreground;
        }

        /**
         * Sets the value of the foreground property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForeground(String value) {
            this.foreground = value;
        }

        /**
         * Gets the value of the background property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBackground() {
            return background;
        }

        /**
         * Sets the value of the background property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBackground(String value) {
            this.background = value;
        }

    }

}
