//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shapeType" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="displayShapeType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="model" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="modelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="displayModelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="documentaiton_plainText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DiagramElementRef")
public class DiagramElementRef {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "shapeType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shapeType;
    @XmlAttribute(name = "displayShapeType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayShapeType;
    @XmlAttribute(name = "model")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String model;
    @XmlAttribute(name = "modelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modelType;
    @XmlAttribute(name = "displayModelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayModelType;
    @XmlAttribute(name = "documentaiton_plainText")
    protected String documentaitonPlainText;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shapeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapeType() {
        return shapeType;
    }

    /**
     * Sets the value of the shapeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapeType(String value) {
        this.shapeType = value;
    }

    /**
     * Gets the value of the displayShapeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayShapeType() {
        return displayShapeType;
    }

    /**
     * Sets the value of the displayShapeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayShapeType(String value) {
        this.displayShapeType = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the displayModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayModelType() {
        return displayModelType;
    }

    /**
     * Sets the value of the displayModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayModelType(String value) {
        this.displayModelType = value;
    }

    /**
     * Gets the value of the documentaitonPlainText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentaitonPlainText() {
        return documentaitonPlainText;
    }

    /**
     * Sets the value of the documentaitonPlainText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentaitonPlainText(String value) {
        this.documentaitonPlainText = value;
    }

}
