//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramRef"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ChildLogicalViewElement" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logicalViewNickName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diagramRef",
    "childLogicalViewElement"
})
@XmlRootElement(name = "LogicalViewElement")
public class LogicalViewElement {

    @XmlElement(name = "DiagramRef")
    protected DiagramRef diagramRef;
    @XmlElement(name = "ChildLogicalViewElement")
    protected ChildLogicalViewElement childLogicalViewElement;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "logicalViewNickName")
    protected String logicalViewNickName;

    /**
     * Gets the value of the diagramRef property.
     * 
     * @return
     *     possible object is
     *     {@link DiagramRef }
     *     
     */
    public DiagramRef getDiagramRef() {
        return diagramRef;
    }

    /**
     * Sets the value of the diagramRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagramRef }
     *     
     */
    public void setDiagramRef(DiagramRef value) {
        this.diagramRef = value;
    }

    /**
     * Gets the value of the childLogicalViewElement property.
     * 
     * @return
     *     possible object is
     *     {@link ChildLogicalViewElement }
     *     
     */
    public ChildLogicalViewElement getChildLogicalViewElement() {
        return childLogicalViewElement;
    }

    /**
     * Sets the value of the childLogicalViewElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildLogicalViewElement }
     *     
     */
    public void setChildLogicalViewElement(ChildLogicalViewElement value) {
        this.childLogicalViewElement = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the logicalViewNickName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalViewNickName() {
        return logicalViewNickName;
    }

    /**
     * Sets the value of the logicalViewNickName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalViewNickName(String value) {
        this.logicalViewNickName = value;
    }

}
