//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramElementProperties" minOccurs="0"/>
 *         &lt;element name="ShapeHeightInfos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="ShapeHeightInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice minOccurs="0">
 *                             &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramElementProperties" minOccurs="0"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diagramElementPropertiesOrShapeHeightInfos"
})
@XmlRootElement(name = "MessageUIModelFlowInfo")
public class MessageUIModelFlowInfo {

    @XmlElements({
        @XmlElement(name = "DiagramElementProperties", type = DiagramElementProperties.class),
        @XmlElement(name = "ShapeHeightInfos", type = MessageUIModelFlowInfo.ShapeHeightInfos.class)
    })
    protected List<Object> diagramElementPropertiesOrShapeHeightInfos;

    /**
     * Gets the value of the diagramElementPropertiesOrShapeHeightInfos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagramElementPropertiesOrShapeHeightInfos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagramElementPropertiesOrShapeHeightInfos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagramElementProperties }
     * {@link MessageUIModelFlowInfo.ShapeHeightInfos }
     * 
     * 
     */
    public List<Object> getDiagramElementPropertiesOrShapeHeightInfos() {
        if (diagramElementPropertiesOrShapeHeightInfos == null) {
            diagramElementPropertiesOrShapeHeightInfos = new ArrayList<Object>();
        }
        return this.diagramElementPropertiesOrShapeHeightInfos;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="ShapeHeightInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice minOccurs="0">
     *                   &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramElementProperties" minOccurs="0"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shapeHeightInfo"
    })
    public static class ShapeHeightInfos {

        @XmlElement(name = "ShapeHeightInfo")
        protected List<MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo> shapeHeightInfo;

        /**
         * Gets the value of the shapeHeightInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shapeHeightInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShapeHeightInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo }
         * 
         * 
         */
        public List<MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo> getShapeHeightInfo() {
            if (shapeHeightInfo == null) {
                shapeHeightInfo = new ArrayList<MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo>();
            }
            return this.shapeHeightInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice minOccurs="0">
         *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}DiagramElementProperties" minOccurs="0"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "diagramElementProperties"
        })
        public static class ShapeHeightInfo {

            @XmlElement(name = "DiagramElementProperties")
            protected DiagramElementProperties diagramElementProperties;

            /**
             * Gets the value of the diagramElementProperties property.
             * 
             * @return
             *     possible object is
             *     {@link DiagramElementProperties }
             *     
             */
            public DiagramElementProperties getDiagramElementProperties() {
                return diagramElementProperties;
            }

            /**
             * Sets the value of the diagramElementProperties property.
             * 
             * @param value
             *     allowed object is
             *     {@link DiagramElementProperties }
             *     
             */
            public void setDiagramElementProperties(DiagramElementProperties value) {
                this.diagramElementProperties = value;
            }

        }

    }

}
