//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ModelProperties" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ChildModels" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}FromSimpleRelationships" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ToSimpleRelationships" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}FromEndRelationships" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ToEndRelationships" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}FromEnd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ToEnd" minOccurs="0"/>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}SubDiagrams" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelId" />
 *       &lt;attribute name="modelType" use="required" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="displayModelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="composite" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="considerDefaultProperties" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="taskTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subprocessTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="triggerModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gatewayTypeModelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="graphicShapeType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelPropertiesAndChildModelsAndFromSimpleRelationships"
})
@XmlRootElement(name = "Model")
public class Model {

    @XmlElements({
        @XmlElement(name = "ModelProperties", type = ModelProperties.class),
        @XmlElement(name = "ChildModels", type = ChildModels.class),
        @XmlElement(name = "FromSimpleRelationships", type = FromSimpleRelationships.class),
        @XmlElement(name = "ToSimpleRelationships", type = ToSimpleRelationships.class),
        @XmlElement(name = "FromEndRelationships", type = FromEndRelationships.class),
        @XmlElement(name = "ToEndRelationships", type = ToEndRelationships.class),
        @XmlElement(name = "FromEnd", type = FromEnd.class),
        @XmlElement(name = "ToEnd", type = ToEnd.class),
        @XmlElement(name = "SubDiagrams", type = SubDiagrams.class)
    })
    protected List<Object> modelPropertiesAndChildModelsAndFromSimpleRelationships;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "modelType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modelType;
    @XmlAttribute(name = "displayModelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayModelType;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "composite")
    protected Boolean composite;
    @XmlAttribute(name = "considerDefaultProperties")
    protected Boolean considerDefaultProperties;
    @XmlAttribute(name = "taskTypeModelType")
    protected String taskTypeModelType;
    @XmlAttribute(name = "subprocessTypeModelType")
    protected String subprocessTypeModelType;
    @XmlAttribute(name = "triggerModelType")
    protected String triggerModelType;
    @XmlAttribute(name = "resultModelType")
    protected String resultModelType;
    @XmlAttribute(name = "gatewayTypeModelType")
    protected String gatewayTypeModelType;
    @XmlAttribute(name = "graphicShapeType")
    protected String graphicShapeType;

    /**
     * Gets the value of the modelPropertiesAndChildModelsAndFromSimpleRelationships property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelPropertiesAndChildModelsAndFromSimpleRelationships property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelPropertiesAndChildModelsAndFromSimpleRelationships().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelProperties }
     * {@link ChildModels }
     * {@link FromSimpleRelationships }
     * {@link ToSimpleRelationships }
     * {@link FromEndRelationships }
     * {@link ToEndRelationships }
     * {@link FromEnd }
     * {@link ToEnd }
     * {@link SubDiagrams }
     * 
     * 
     */
    public List<Object> getModelPropertiesAndChildModelsAndFromSimpleRelationships() {
        if (modelPropertiesAndChildModelsAndFromSimpleRelationships == null) {
            modelPropertiesAndChildModelsAndFromSimpleRelationships = new ArrayList<Object>();
        }
        return this.modelPropertiesAndChildModelsAndFromSimpleRelationships;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the displayModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayModelType() {
        return displayModelType;
    }

    /**
     * Sets the value of the displayModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayModelType(String value) {
        this.displayModelType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the composite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isComposite() {
        if (composite == null) {
            return false;
        } else {
            return composite;
        }
    }

    /**
     * Sets the value of the composite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setComposite(Boolean value) {
        this.composite = value;
    }

    /**
     * Gets the value of the considerDefaultProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConsiderDefaultProperties() {
        if (considerDefaultProperties == null) {
            return false;
        } else {
            return considerDefaultProperties;
        }
    }

    /**
     * Sets the value of the considerDefaultProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConsiderDefaultProperties(Boolean value) {
        this.considerDefaultProperties = value;
    }

    /**
     * Gets the value of the taskTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskTypeModelType() {
        return taskTypeModelType;
    }

    /**
     * Sets the value of the taskTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskTypeModelType(String value) {
        this.taskTypeModelType = value;
    }

    /**
     * Gets the value of the subprocessTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubprocessTypeModelType() {
        return subprocessTypeModelType;
    }

    /**
     * Sets the value of the subprocessTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubprocessTypeModelType(String value) {
        this.subprocessTypeModelType = value;
    }

    /**
     * Gets the value of the triggerModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggerModelType() {
        return triggerModelType;
    }

    /**
     * Sets the value of the triggerModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggerModelType(String value) {
        this.triggerModelType = value;
    }

    /**
     * Gets the value of the resultModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultModelType() {
        return resultModelType;
    }

    /**
     * Sets the value of the resultModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultModelType(String value) {
        this.resultModelType = value;
    }

    /**
     * Gets the value of the gatewayTypeModelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayTypeModelType() {
        return gatewayTypeModelType;
    }

    /**
     * Sets the value of the gatewayTypeModelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayTypeModelType(String value) {
        this.gatewayTypeModelType = value;
    }

    /**
     * Gets the value of the graphicShapeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicShapeType() {
        return graphicShapeType;
    }

    /**
     * Sets the value of the graphicShapeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicShapeType(String value) {
        this.graphicShapeType = value;
    }

}
