//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visual-paradigm.com/product/vpuml/modelexporter}property">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.visual-paradigm.com/product/vpuml/modelexporter}ModelRef" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelRef"
})
@XmlRootElement(name = "ModelRefProperty")
public class ModelRefProperty
    extends Property
{

    @XmlElement(name = "ModelRef")
    protected ModelRef modelRef;

    /**
     * Gets the value of the modelRef property.
     * 
     * @return
     *     possible object is
     *     {@link ModelRef }
     *     
     */
    public ModelRef getModelRef() {
        return modelRef;
    }

    /**
     * Sets the value of the modelRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelRef }
     *     
     */
    public void setModelRef(ModelRef value) {
        this.modelRef = value;
    }

}
