//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the object package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModelRef_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ModelRef");
    private final static QName _RelationshipRef_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "RelationshipRef");
    private final static QName _DiagramHiddenDiagramElements_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "HiddenDiagramElements");
    private final static QName _DiagramShowAsNoneArtifacts_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsNoneArtifacts");
    private final static QName _DiagramShowAsKeywordAndIconArtifacts_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsKeywordAndIconArtifacts");
    private final static QName _DiagramShowAsIconArtifacts_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsIconArtifacts");
    private final static QName _DiagramShowAsIconComponents_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsIconComponents");
    private final static QName _DiagramShowAsKeywordAndIconComponents_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsKeywordAndIconComponents");
    private final static QName _DiagramShowAsKeywordComponents_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsKeywordComponents");
    private final static QName _DiagramShowAsNoneComponents_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsNoneComponents");
    private final static QName _DiagramShowAsKeywordArtifacts_QNAME = new QName("http://www.visual-paradigm.com/product/vpuml/modelexporter", "ShowAsKeywordArtifacts");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: object
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StringArrayProperty }
     * 
     */
    public StringArrayProperty createStringArrayProperty() {
        return new StringArrayProperty();
    }

    /**
     * Create an instance of {@link IntArrayProperty }
     * 
     */
    public IntArrayProperty createIntArrayProperty() {
        return new IntArrayProperty();
    }

    /**
     * Create an instance of {@link Scenarios }
     * 
     */
    public Scenarios createScenarios() {
        return new Scenarios();
    }

    /**
     * Create an instance of {@link TextModelProperty }
     * 
     */
    public TextModelProperty createTextModelProperty() {
        return new TextModelProperty();
    }

    /**
     * Create an instance of {@link TempFiles }
     * 
     */
    public TempFiles createTempFiles() {
        return new TempFiles();
    }

    /**
     * Create an instance of {@link DiagramComments }
     * 
     */
    public DiagramComments createDiagramComments() {
        return new DiagramComments();
    }

    /**
     * Create an instance of {@link ShapeGroups }
     * 
     */
    public ShapeGroups createShapeGroups() {
        return new ShapeGroups();
    }

    /**
     * Create an instance of {@link LayersModel }
     * 
     */
    public LayersModel createLayersModel() {
        return new LayersModel();
    }

    /**
     * Create an instance of {@link Lifelines }
     * 
     */
    public Lifelines createLifelines() {
        return new Lifelines();
    }

    /**
     * Create an instance of {@link TimeUnits }
     * 
     */
    public TimeUnits createTimeUnits() {
        return new TimeUnits();
    }

    /**
     * Create an instance of {@link ColumnWidthInfos }
     * 
     */
    public ColumnWidthInfos createColumnWidthInfos() {
        return new ColumnWidthInfos();
    }

    /**
     * Create an instance of {@link ColumnFilterInfos }
     * 
     */
    public ColumnFilterInfos createColumnFilterInfos() {
        return new ColumnFilterInfos();
    }

    /**
     * Create an instance of {@link FreehandPoints }
     * 
     */
    public FreehandPoints createFreehandPoints() {
        return new FreehandPoints();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Icons }
     * 
     */
    public Icons createIcons() {
        return new Icons();
    }

    /**
     * Create an instance of {@link Rows }
     * 
     */
    public Rows createRows() {
        return new Rows();
    }

    /**
     * Create an instance of {@link MessageUIModelFlowInfo }
     * 
     */
    public MessageUIModelFlowInfo createMessageUIModelFlowInfo() {
        return new MessageUIModelFlowInfo();
    }

    /**
     * Create an instance of {@link CompartmentColorModels }
     * 
     */
    public CompartmentColorModels createCompartmentColorModels() {
        return new CompartmentColorModels();
    }

    /**
     * Create an instance of {@link Connector }
     * 
     */
    public Connector createConnector() {
        return new Connector();
    }

    /**
     * Create an instance of {@link ORMInfo }
     * 
     */
    public ORMInfo createORMInfo() {
        return new ORMInfo();
    }

    /**
     * Create an instance of {@link RequirementEnumerationInfo }
     * 
     */
    public RequirementEnumerationInfo createRequirementEnumerationInfo() {
        return new RequirementEnumerationInfo();
    }

    /**
     * Create an instance of {@link DiagramOptions }
     * 
     */
    public DiagramOptions createDiagramOptions() {
        return new DiagramOptions();
    }

    /**
     * Create an instance of {@link RequirementEnumerationInfo.RequirementEnumeration }
     * 
     */
    public RequirementEnumerationInfo.RequirementEnumeration createRequirementEnumerationInfoRequirementEnumeration() {
        return new RequirementEnumerationInfo.RequirementEnumeration();
    }

    /**
     * Create an instance of {@link RequirementEnumerationInfo.RequirementEnumeration.DeletedItems }
     * 
     */
    public RequirementEnumerationInfo.RequirementEnumeration.DeletedItems createRequirementEnumerationInfoRequirementEnumerationDeletedItems() {
        return new RequirementEnumerationInfo.RequirementEnumeration.DeletedItems();
    }

    /**
     * Create an instance of {@link RequirementEnumerationInfo.RequirementEnumeration.Items }
     * 
     */
    public RequirementEnumerationInfo.RequirementEnumeration.Items createRequirementEnumerationInfoRequirementEnumerationItems() {
        return new RequirementEnumerationInfo.RequirementEnumeration.Items();
    }

    /**
     * Create an instance of {@link Connector.Points }
     * 
     */
    public Connector.Points createConnectorPoints() {
        return new Connector.Points();
    }

    /**
     * Create an instance of {@link MessageUIModelFlowInfo.ShapeHeightInfos }
     * 
     */
    public MessageUIModelFlowInfo.ShapeHeightInfos createMessageUIModelFlowInfoShapeHeightInfos() {
        return new MessageUIModelFlowInfo.ShapeHeightInfos();
    }

    /**
     * Create an instance of {@link Line.Stroke }
     * 
     */
    public Line.Stroke createLineStroke() {
        return new Line.Stroke();
    }

    /**
     * Create an instance of {@link Line.Stroke.Dashes }
     * 
     */
    public Line.Stroke.Dashes createLineStrokeDashes() {
        return new Line.Stroke.Dashes();
    }

    /**
     * Create an instance of {@link ArrowHead }
     * 
     */
    public ArrowHead createArrowHead() {
        return new ArrowHead();
    }

    /**
     * Create an instance of {@link ArrowHead.ShapeHeightInfos }
     * 
     */
    public ArrowHead.ShapeHeightInfos createArrowHeadShapeHeightInfos() {
        return new ArrowHead.ShapeHeightInfos();
    }

    /**
     * Create an instance of {@link Lifelines.Lifeline }
     * 
     */
    public Lifelines.Lifeline createLifelinesLifeline() {
        return new Lifelines.Lifeline();
    }

    /**
     * Create an instance of {@link Lifelines.Lifeline.StateConditions }
     * 
     */
    public Lifelines.Lifeline.StateConditions createLifelinesLifelineStateConditions() {
        return new Lifelines.Lifeline.StateConditions();
    }

    /**
     * Create an instance of {@link DiagramComments.DiagramComment }
     * 
     */
    public DiagramComments.DiagramComment createDiagramCommentsDiagramComment() {
        return new DiagramComments.DiagramComment();
    }

    /**
     * Create an instance of {@link Scenarios.Scenario }
     * 
     */
    public Scenarios.Scenario createScenariosScenario() {
        return new Scenarios.Scenario();
    }

    /**
     * Create an instance of {@link Scenarios.Scenario.ScenarioActions }
     * 
     */
    public Scenarios.Scenario.ScenarioActions createScenariosScenarioScenarioActions() {
        return new Scenarios.Scenario.ScenarioActions();
    }

    /**
     * Create an instance of {@link IntArrayProperty.Values }
     * 
     */
    public IntArrayProperty.Values createIntArrayPropertyValues() {
        return new IntArrayProperty.Values();
    }

    /**
     * Create an instance of {@link StringArrayProperty.Values }
     * 
     */
    public StringArrayProperty.Values createStringArrayPropertyValues() {
        return new StringArrayProperty.Values();
    }

    /**
     * Create an instance of {@link DiagramElementRefsProperty }
     * 
     */
    public DiagramElementRefsProperty createDiagramElementRefsProperty() {
        return new DiagramElementRefsProperty();
    }

    /**
     * Create an instance of {@link DiagramElementRef }
     * 
     */
    public DiagramElementRef createDiagramElementRef() {
        return new DiagramElementRef();
    }

    /**
     * Create an instance of {@link Diagrams }
     * 
     */
    public Diagrams createDiagrams() {
        return new Diagrams();
    }

    /**
     * Create an instance of {@link Diagram }
     * 
     */
    public Diagram createDiagram() {
        return new Diagram();
    }

    /**
     * Create an instance of {@link DiagramProperties }
     * 
     */
    public DiagramProperties createDiagramProperties() {
        return new DiagramProperties();
    }

    /**
     * Create an instance of {@link StringProperty }
     * 
     */
    public StringProperty createStringProperty() {
        return new StringProperty();
    }

    /**
     * Create an instance of {@link IntegerProperty }
     * 
     */
    public IntegerProperty createIntegerProperty() {
        return new IntegerProperty();
    }

    /**
     * Create an instance of {@link BooleanProperty }
     * 
     */
    public BooleanProperty createBooleanProperty() {
        return new BooleanProperty();
    }

    /**
     * Create an instance of {@link DoubleProperty }
     * 
     */
    public DoubleProperty createDoubleProperty() {
        return new DoubleProperty();
    }

    /**
     * Create an instance of {@link LongProperty }
     * 
     */
    public LongProperty createLongProperty() {
        return new LongProperty();
    }

    /**
     * Create an instance of {@link ColorProperty }
     * 
     */
    public ColorProperty createColorProperty() {
        return new ColorProperty();
    }

    /**
     * Create an instance of {@link ModelRefProperty }
     * 
     */
    public ModelRefProperty createModelRefProperty() {
        return new ModelRefProperty();
    }

    /**
     * Create an instance of {@link ModelRef }
     * 
     */
    public ModelRef createModelRef() {
        return new ModelRef();
    }

    /**
     * Create an instance of {@link DiagramRefProperty }
     * 
     */
    public DiagramRefProperty createDiagramRefProperty() {
        return new DiagramRefProperty();
    }

    /**
     * Create an instance of {@link DiagramRef }
     * 
     */
    public DiagramRef createDiagramRef() {
        return new DiagramRef();
    }

    /**
     * Create an instance of {@link StringArrayProperty.Value }
     * 
     */
    public StringArrayProperty.Value createStringArrayPropertyValue() {
        return new StringArrayProperty.Value();
    }

    /**
     * Create an instance of {@link ModelsRefs }
     * 
     */
    public ModelsRefs createModelsRefs() {
        return new ModelsRefs();
    }

    /**
     * Create an instance of {@link GridColumns }
     * 
     */
    public GridColumns createGridColumns() {
        return new GridColumns();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link ModelProperties }
     * 
     */
    public ModelProperties createModelProperties() {
        return new ModelProperties();
    }

    /**
     * Create an instance of {@link HTMLProperty }
     * 
     */
    public HTMLProperty createHTMLProperty() {
        return new HTMLProperty();
    }

    /**
     * Create an instance of {@link ModelProperty }
     * 
     */
    public ModelProperty createModelProperty() {
        return new ModelProperty();
    }

    /**
     * Create an instance of {@link ModelsProperty }
     * 
     */
    public ModelsProperty createModelsProperty() {
        return new ModelsProperty();
    }

    /**
     * Create an instance of {@link ModelRefsProperty }
     * 
     */
    public ModelRefsProperty createModelRefsProperty() {
        return new ModelRefsProperty();
    }

    /**
     * Create an instance of {@link TextModelProperty.StringValue }
     * 
     */
    public TextModelProperty.StringValue createTextModelPropertyStringValue() {
        return new TextModelProperty.StringValue();
    }

    /**
     * Create an instance of {@link DiagramElementRefProperty }
     * 
     */
    public DiagramElementRefProperty createDiagramElementRefProperty() {
        return new DiagramElementRefProperty();
    }

    /**
     * Create an instance of {@link ChildModels }
     * 
     */
    public ChildModels createChildModels() {
        return new ChildModels();
    }

    /**
     * Create an instance of {@link FromSimpleRelationships }
     * 
     */
    public FromSimpleRelationships createFromSimpleRelationships() {
        return new FromSimpleRelationships();
    }

    /**
     * Create an instance of {@link RelationshipRef }
     * 
     */
    public RelationshipRef createRelationshipRef() {
        return new RelationshipRef();
    }

    /**
     * Create an instance of {@link ToSimpleRelationships }
     * 
     */
    public ToSimpleRelationships createToSimpleRelationships() {
        return new ToSimpleRelationships();
    }

    /**
     * Create an instance of {@link FromEndRelationships }
     * 
     */
    public FromEndRelationships createFromEndRelationships() {
        return new FromEndRelationships();
    }

    /**
     * Create an instance of {@link ToEndRelationships }
     * 
     */
    public ToEndRelationships createToEndRelationships() {
        return new ToEndRelationships();
    }

    /**
     * Create an instance of {@link FromEnd }
     * 
     */
    public FromEnd createFromEnd() {
        return new FromEnd();
    }

    /**
     * Create an instance of {@link ToEnd }
     * 
     */
    public ToEnd createToEnd() {
        return new ToEnd();
    }

    /**
     * Create an instance of {@link SubDiagrams }
     * 
     */
    public SubDiagrams createSubDiagrams() {
        return new SubDiagrams();
    }

    /**
     * Create an instance of {@link TempFiles.TempFile }
     * 
     */
    public TempFiles.TempFile createTempFilesTempFile() {
        return new TempFiles.TempFile();
    }

    /**
     * Create an instance of {@link ShapeGroups.ShapeGroup }
     * 
     */
    public ShapeGroups.ShapeGroup createShapeGroupsShapeGroup() {
        return new ShapeGroups.ShapeGroup();
    }

    /**
     * Create an instance of {@link LayersModel.Layer }
     * 
     */
    public LayersModel.Layer createLayersModelLayer() {
        return new LayersModel.Layer();
    }

    /**
     * Create an instance of {@link Shapes }
     * 
     */
    public Shapes createShapes() {
        return new Shapes();
    }

    /**
     * Create an instance of {@link Shape }
     * 
     */
    public Shape createShape() {
        return new Shape();
    }

    /**
     * Create an instance of {@link DiagramElementProperties }
     * 
     */
    public DiagramElementProperties createDiagramElementProperties() {
        return new DiagramElementProperties();
    }

    /**
     * Create an instance of {@link PointProperty }
     * 
     */
    public PointProperty createPointProperty() {
        return new PointProperty();
    }

    /**
     * Create an instance of {@link RectangleProperty }
     * 
     */
    public RectangleProperty createRectangleProperty() {
        return new RectangleProperty();
    }

    /**
     * Create an instance of {@link DimensionProperty }
     * 
     */
    public DimensionProperty createDimensionProperty() {
        return new DimensionProperty();
    }

    /**
     * Create an instance of {@link ClauseRegions }
     * 
     */
    public ClauseRegions createClauseRegions() {
        return new ClauseRegions();
    }

    /**
     * Create an instance of {@link ClauseRegion }
     * 
     */
    public ClauseRegion createClauseRegion() {
        return new ClauseRegion();
    }

    /**
     * Create an instance of {@link ElseRegion }
     * 
     */
    public ElseRegion createElseRegion() {
        return new ElseRegion();
    }

    /**
     * Create an instance of {@link TimeUnits.TimeUnit }
     * 
     */
    public TimeUnits.TimeUnit createTimeUnitsTimeUnit() {
        return new TimeUnits.TimeUnit();
    }

    /**
     * Create an instance of {@link ColumnWidthInfos.ColumnWidthInfo }
     * 
     */
    public ColumnWidthInfos.ColumnWidthInfo createColumnWidthInfosColumnWidthInfo() {
        return new ColumnWidthInfos.ColumnWidthInfo();
    }

    /**
     * Create an instance of {@link ColumnFilterInfos.ColumnFilterInfo }
     * 
     */
    public ColumnFilterInfos.ColumnFilterInfo createColumnFilterInfosColumnFilterInfo() {
        return new ColumnFilterInfos.ColumnFilterInfo();
    }

    /**
     * Create an instance of {@link DurationConstraints }
     * 
     */
    public DurationConstraints createDurationConstraints() {
        return new DurationConstraints();
    }

    /**
     * Create an instance of {@link FreehandPoints.Point }
     * 
     */
    public FreehandPoints.Point createFreehandPointsPoint() {
        return new FreehandPoints.Point();
    }

    /**
     * Create an instance of {@link ElementFont }
     * 
     */
    public ElementFont createElementFont() {
        return new ElementFont();
    }

    /**
     * Create an instance of {@link Icons.Value }
     * 
     */
    public Icons.Value createIconsValue() {
        return new Icons.Value();
    }

    /**
     * Create an instance of {@link Rows.Row }
     * 
     */
    public Rows.Row createRowsRow() {
        return new Rows.Row();
    }

    /**
     * Create an instance of {@link ChildShapes }
     * 
     */
    public ChildShapes createChildShapes() {
        return new ChildShapes();
    }

    /**
     * Create an instance of {@link FillColor }
     * 
     */
    public FillColor createFillColor() {
        return new FillColor();
    }

    /**
     * Create an instance of {@link object.visualparadigm.ShapeGroup }
     * 
     */
    public object.visualparadigm.ShapeGroup createShapeGroup() {
        return new object.visualparadigm.ShapeGroup();
    }

    /**
     * Create an instance of {@link CompartmentFont }
     * 
     */
    public CompartmentFont createCompartmentFont() {
        return new CompartmentFont();
    }

    /**
     * Create an instance of {@link CompartmentColorModels.CompartmentColorModel }
     * 
     */
    public CompartmentColorModels.CompartmentColorModel createCompartmentColorModelsCompartmentColorModel() {
        return new CompartmentColorModels.CompartmentColorModel();
    }

    /**
     * Create an instance of {@link Connectors }
     * 
     */
    public Connectors createConnectors() {
        return new Connectors();
    }

    /**
     * Create an instance of {@link ProjectInfo }
     * 
     */
    public ProjectInfo createProjectInfo() {
        return new ProjectInfo();
    }

    /**
     * Create an instance of {@link ORMInfo.DefaultClassDiagram }
     * 
     */
    public ORMInfo.DefaultClassDiagram createORMInfoDefaultClassDiagram() {
        return new ORMInfo.DefaultClassDiagram();
    }

    /**
     * Create an instance of {@link ORMInfo.DefaultERD }
     * 
     */
    public ORMInfo.DefaultERD createORMInfoDefaultERD() {
        return new ORMInfo.DefaultERD();
    }

    /**
     * Create an instance of {@link LogicalView }
     * 
     */
    public LogicalView createLogicalView() {
        return new LogicalView();
    }

    /**
     * Create an instance of {@link LogicalViewElement }
     * 
     */
    public LogicalViewElement createLogicalViewElement() {
        return new LogicalViewElement();
    }

    /**
     * Create an instance of {@link ChildLogicalViewElement }
     * 
     */
    public ChildLogicalViewElement createChildLogicalViewElement() {
        return new ChildLogicalViewElement();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Models }
     * 
     */
    public Models createModels() {
        return new Models();
    }

    /**
     * Create an instance of {@link DiagramOptions.DefaultHtmlDocFont }
     * 
     */
    public DiagramOptions.DefaultHtmlDocFont createDiagramOptionsDefaultHtmlDocFont() {
        return new DiagramOptions.DefaultHtmlDocFont();
    }

    /**
     * Create an instance of {@link RequirementEnumerationInfo.RequirementEnumeration.DeletedItems.Item }
     * 
     */
    public RequirementEnumerationInfo.RequirementEnumeration.DeletedItems.Item createRequirementEnumerationInfoRequirementEnumerationDeletedItemsItem() {
        return new RequirementEnumerationInfo.RequirementEnumeration.DeletedItems.Item();
    }

    /**
     * Create an instance of {@link RequirementEnumerationInfo.RequirementEnumeration.Items.Item }
     * 
     */
    public RequirementEnumerationInfo.RequirementEnumeration.Items.Item createRequirementEnumerationInfoRequirementEnumerationItemsItem() {
        return new RequirementEnumerationInfo.RequirementEnumeration.Items.Item();
    }

    /**
     * Create an instance of {@link Connector.Points.Point }
     * 
     */
    public Connector.Points.Point createConnectorPointsPoint() {
        return new Connector.Points.Point();
    }

    /**
     * Create an instance of {@link MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo }
     * 
     */
    public MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo createMessageUIModelFlowInfoShapeHeightInfosShapeHeightInfo() {
        return new MessageUIModelFlowInfo.ShapeHeightInfos.ShapeHeightInfo();
    }

    /**
     * Create an instance of {@link Line.Stroke.Dashes.Dash }
     * 
     */
    public Line.Stroke.Dashes.Dash createLineStrokeDashesDash() {
        return new Line.Stroke.Dashes.Dash();
    }

    /**
     * Create an instance of {@link ArrowHead.ShapeHeightInfos.ShapeHeightInfo }
     * 
     */
    public ArrowHead.ShapeHeightInfos.ShapeHeightInfo createArrowHeadShapeHeightInfosShapeHeightInfo() {
        return new ArrowHead.ShapeHeightInfos.ShapeHeightInfo();
    }

    /**
     * Create an instance of {@link Lifelines.Lifeline.StateConditions.StateCondition }
     * 
     */
    public Lifelines.Lifeline.StateConditions.StateCondition createLifelinesLifelineStateConditionsStateCondition() {
        return new Lifelines.Lifeline.StateConditions.StateCondition();
    }

    /**
     * Create an instance of {@link DiagramComments.DiagramComment.DiagramCommentProperties }
     * 
     */
    public DiagramComments.DiagramComment.DiagramCommentProperties createDiagramCommentsDiagramCommentDiagramCommentProperties() {
        return new DiagramComments.DiagramComment.DiagramCommentProperties();
    }

    /**
     * Create an instance of {@link Scenarios.Scenario.ScenarioActions.ScenarioAction }
     * 
     */
    public Scenarios.Scenario.ScenarioActions.ScenarioAction createScenariosScenarioScenarioActionsScenarioAction() {
        return new Scenarios.Scenario.ScenarioActions.ScenarioAction();
    }

    /**
     * Create an instance of {@link IntArrayProperty.Values.Value }
     * 
     */
    public IntArrayProperty.Values.Value createIntArrayPropertyValuesValue() {
        return new IntArrayProperty.Values.Value();
    }

    /**
     * Create an instance of {@link StringArrayProperty.Values.Value }
     * 
     */
    public StringArrayProperty.Values.Value createStringArrayPropertyValuesValue() {
        return new StringArrayProperty.Values.Value();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ModelRef")
    public JAXBElement<ModelRef> createModelRef(ModelRef value) {
        return new JAXBElement<ModelRef>(_ModelRef_QNAME, ModelRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "RelationshipRef")
    public JAXBElement<RelationshipRef> createRelationshipRef(RelationshipRef value) {
        return new JAXBElement<RelationshipRef>(_RelationshipRef_QNAME, RelationshipRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "HiddenDiagramElements", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramHiddenDiagramElements(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramHiddenDiagramElements_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsNoneArtifacts", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsNoneArtifacts(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsNoneArtifacts_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsKeywordAndIconArtifacts", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsKeywordAndIconArtifacts(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsKeywordAndIconArtifacts_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsIconArtifacts", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsIconArtifacts(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsIconArtifacts_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsIconComponents", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsIconComponents(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsIconComponents_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsKeywordAndIconComponents", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsKeywordAndIconComponents(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsKeywordAndIconComponents_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsKeywordComponents", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsKeywordComponents(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsKeywordComponents_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsNoneComponents", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsNoneComponents(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsNoneComponents_QNAME, ModelsRefs.class, Diagram.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelsRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visual-paradigm.com/product/vpuml/modelexporter", name = "ShowAsKeywordArtifacts", scope = Diagram.class)
    public JAXBElement<ModelsRefs> createDiagramShowAsKeywordArtifacts(ModelsRefs value) {
        return new JAXBElement<ModelsRefs>(_DiagramShowAsKeywordArtifacts_QNAME, ModelsRefs.class, Diagram.class, value);
    }

}
