//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.17 at 08:40:10 PM ICT 
//


package object.visualparadigm;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visual-paradigm.com/product/vpuml/modelexporter}property">
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="internalValue" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="pathName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="diagramName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="diagramType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="displayDiagramType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="modelType" type="{http://www.visual-paradigm.com/product/vpuml/modelexporter}modelType" />
 *       &lt;attribute name="shapeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="imageValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rtfValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "StringProperty")
public class StringProperty
    extends Property
{

    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "internalValue")
    protected BigInteger internalValue;
    @XmlAttribute(name = "pathName")
    protected String pathName;
    @XmlAttribute(name = "fileName")
    protected String fileName;
    @XmlAttribute(name = "fileValue")
    protected String fileValue;
    @XmlAttribute(name = "diagramName")
    protected String diagramName;
    @XmlAttribute(name = "diagramType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String diagramType;
    @XmlAttribute(name = "displayDiagramType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayDiagramType;
    @XmlAttribute(name = "modelType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modelType;
    @XmlAttribute(name = "shapeName")
    protected String shapeName;
    @XmlAttribute(name = "imageValue")
    protected String imageValue;
    @XmlAttribute(name = "rtfValue")
    protected String rtfValue;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the internalValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInternalValue() {
        return internalValue;
    }

    /**
     * Sets the value of the internalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInternalValue(BigInteger value) {
        this.internalValue = value;
    }

    /**
     * Gets the value of the pathName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathName() {
        return pathName;
    }

    /**
     * Sets the value of the pathName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathName(String value) {
        this.pathName = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the fileValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileValue() {
        return fileValue;
    }

    /**
     * Sets the value of the fileValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileValue(String value) {
        this.fileValue = value;
    }

    /**
     * Gets the value of the diagramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagramName() {
        return diagramName;
    }

    /**
     * Sets the value of the diagramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagramName(String value) {
        this.diagramName = value;
    }

    /**
     * Gets the value of the diagramType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagramType() {
        return diagramType;
    }

    /**
     * Sets the value of the diagramType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagramType(String value) {
        this.diagramType = value;
    }

    /**
     * Gets the value of the displayDiagramType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayDiagramType() {
        return displayDiagramType;
    }

    /**
     * Sets the value of the displayDiagramType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayDiagramType(String value) {
        this.displayDiagramType = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelType(String value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the shapeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapeName() {
        return shapeName;
    }

    /**
     * Sets the value of the shapeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapeName(String value) {
        this.shapeName = value;
    }

    /**
     * Gets the value of the imageValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageValue() {
        return imageValue;
    }

    /**
     * Sets the value of the imageValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageValue(String value) {
        this.imageValue = value;
    }

    /**
     * Gets the value of the rtfValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtfValue() {
        return rtfValue;
    }

    /**
     * Sets the value of the rtfValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtfValue(String value) {
        this.rtfValue = value;
    }

}
